language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t danielfleace/react-test ./client/Dockerfile.dev

script:
  - docker build -t danielfleace/react-test npm test

after_sucess:
  - docker build -t danielfleace/multi-client ./client
  - docker build -t danielfleace/multi-nginx ./nginx
  - docker build -t danielfleace/multi-worker ./worker
  - docker build -t danielfleace/multi-server ./server
