language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t danielfleace/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true danielfleace/react-test npm test

after_sucess:
  - docker build -t danielfleace/multi-client ./client
  - docker build -t danielfleace/multi-nginx ./nginx
  - docker build -t danielfleace/multi-worker ./worker
  - docker build -t danielfleace/multi-server ./server

# Log into the docker CLI
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# push images to docker hub
- docker push danielfleace/multi-client
- docker push danielfleace/multi-nginx
- docker push danielfleace/multi-worker
- docker push danielfleace/multi-server
